### ISSUE TITLE
Discovered Bugs

### ISSUE THREAD

**Issue by Ahmedrali** [franzen/babelphish#1]
## In Generated Java File:
- Neet to import:
  - java.io.ByteArrayInputStream
  - java.io.ByteArrayOutputStream
  - java.io.IOException
  - java.nio.charset.Charset
  - java.util.ArrayList
  - java.util.HashMap
- In writeInt32: 0xFFFFFFFF needs to be 0xFFFFFFFFL
  - 0xFFFFFFFF = -1 while 0xFFFFFFFFL = 4.294.967.29 "Max Value"
- In writeIpNumber: 
  - split(".") needs to be split("\.") because split function takes (String regex)
  - Need check of if v.equals("")
    - Integer.parseInt(bs[i]) raise error because of bs contains empty value. (bs = [""])
- In writeBinary: 0xFFFFFFFF needs to be 0xFFFFFFFFL
- In readBinary:
  - "return readBytes((int) readInt32(data), data)" raise error because of readInt32(data) = -1 "EOF", 
    it needs to be "return readBytes((int) c, data)"
## In Generated Ruby File:
- In write_binary: it takes either list or string while read_binary always return string.

**Comment by franzen** [comment]
1. JAVA: The code generation should save all classes in different files with the above imports. I have'nt had time to do this yet. But feel free to improve it ;) If u find bugs, fix them directly in the code generation.

You just run "rake install" to install your version of gem and you can continue to test with your fixes in place
1. RUBY: In write_binary: it takes either list or string while read_binary always return string.
   I don't really know which approach to take in this case, since we can't really return both a list and a string. Ruby strings are the closest thing to a bytearray (to my knowledge)... Thats why I took that path... If u have any other suggestions, please let me know
